#define _POSIX_C_SOURCE 200809L
#define _GNU_SOURCE
#pragma GCC diagnostic ignored "-Wunused-result"

#include "init.h"
#include "../util/log.h"
#include "../util/paths.h"
#include "../util/fs.h"
#include "../mcugen.h"
#include <stdio.h>
#include <unistd.h>

void cmd_init(void) {
    char dir[MAX_PATH]; xdg_config_dir(dir, sizeof(dir));
    char cfgpath[MAX_PATH]; snprintf(cfgpath, sizeof(cfgpath), "%s/config.toml", dir);
    char tpldir[MAX_PATH];  snprintf(tpldir,  sizeof(tpldir),  "%s/templates", dir);
    char tplpath[MAX_PATH]; snprintf(tplpath, sizeof(tplpath), "%s/example.css", tpldir);

    mkdirs_local(tpldir);

    if (access(cfgpath, F_OK)==0) {
        printf("config already exists: %s\n", cfgpath);
    } else {
        const char *cfg =
            "# mcugen v3 configuration\n"
            "# ~/.config/mcugen/config.toml\n\n"
            "[config]\n"
            "default_mode = \"light\"       # light | dark\n"
            "default_type = \"tonal-spot\"  # tonal-spot | vibrant | expressive |\n"
            "#                             # fidelity | monochrome | neutral |\n"
            "#                             # fruit-salad | rainbow | content\n"
            "caching      = false\n\n"
            "# ---- Custom colors (optionally harmonized to seed) ----\n"
            "# [colors.green]\n"
            "# color = \"#4CAF50\"\n"
            "# blend = true\n\n"
            "# ---- Templates ----\n"
            "[templates.example]\n"
            "input_path   = \"~/.config/mcugen/templates/example.css\"\n"
            "output_path  = \"~/.config/mcugen/output/example.css\"\n"
            "# post_hook  = \"echo done\"\n\n"
            "# [templates.waybar]\n"
            "# input_path    = \"~/.config/mcugen/templates/waybar.css\"\n"
            "# output_path   = \"~/.config/waybar/style.css\"\n"
            "# output_path   = \"~/.config/waybar2/style.css\"\n"
            "# post_hook     = \"pkill -SIGUSR2 waybar\"\n";
        write_file(cfgpath, cfg);
        printf("created: %s\n", cfgpath);
    }

    if (access(tplpath, F_OK)==0) {
        printf("template already exists: %s\n", tplpath);
    } else {
        const char *tpl =
            "/* Generated by mcugen v3 — {{colors.primary.hex}} */\n"
            ":root {\n"
            "  --md-primary:                    {{colors.primary.hex}};\n"
            "  --md-on-primary:                 {{colors.on_primary.hex}};\n"
            "  --md-primary-container:          {{colors.primary_container.hex}};\n"
            "  --md-on-primary-container:       {{colors.on_primary_container.hex}};\n"
            "  --md-inverse-primary:            {{colors.inverse_primary.hex}};\n"
            "  --md-secondary:                  {{colors.secondary.hex}};\n"
            "  --md-on-secondary:               {{colors.on_secondary.hex}};\n"
            "  --md-secondary-container:        {{colors.secondary_container.hex}};\n"
            "  --md-on-secondary-container:     {{colors.on_secondary_container.hex}};\n"
            "  --md-tertiary:                   {{colors.tertiary.hex}};\n"
            "  --md-on-tertiary:                {{colors.on_tertiary.hex}};\n"
            "  --md-tertiary-container:         {{colors.tertiary_container.hex}};\n"
            "  --md-on-tertiary-container:      {{colors.on_tertiary_container.hex}};\n"
            "  --md-error:                      {{colors.error.hex}};\n"
            "  --md-on-error:                   {{colors.on_error.hex}};\n"
            "  --md-surface:                    {{colors.surface.hex}};\n"
            "  --md-on-surface:                 {{colors.on_surface.hex}};\n"
            "  --md-surface-variant:            {{colors.surface_variant.hex}};\n"
            "  --md-on-surface-variant:         {{colors.on_surface_variant.hex}};\n"
            "  --md-surface-container:          {{colors.surface_container.hex}};\n"
            "  --md-background:                 {{colors.background.hex}};\n"
            "  --md-on-background:              {{colors.on_background.hex}};\n"
            "  --md-outline:                    {{colors.outline.hex}};\n"
            "  --md-outline-variant:            {{colors.outline_variant.hex}};\n"
            "  --md-inverse-surface:            {{colors.inverse_surface.hex}};\n"
            "  --md-inverse-on-surface:         {{colors.inverse_on_surface.hex}};\n"
            "  --md-primary-rgb:                {{colors.primary.rgb_raw}};\n"
            "  --md-primary-light:              {{colors.primary.light.hex}};\n"
            "  --md-primary-dark:               {{colors.primary.dark.hex}};\n"
            "}\n";
        write_file(tplpath, tpl);
        printf("created: %s\n", tplpath);
    }

    printf("\nQuick start:\n");
    printf("  mcugen image ~/Pictures/wallpaper.jpg\n");
    printf("  mcugen color \"#6750A4\" --mode dark\n");
    printf("  mcugen color \"#6750A4\" --type vibrant\n");
    printf("  mcugen show color \"#6750A4\" --json\n");
    printf("  mcugen blend \"#6750A4\" \"#1DB954\"\n");
    printf("  mcugen save mytheme && mcugen use mytheme\n");
    printf("  mcugen check\n");
}
