#define _POSIX_C_SOURCE 200809L
#define _GNU_SOURCE
#pragma GCC diagnostic ignored "-Wunused-result"

#include "init.h"
#include "../util/log.h"
#include "../util/paths.h"
#include "../util/fs.h"
#include "../mcugen.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

/*
 * GTK-4 / libadwaita template.
 *
 * Mapping logic follows real-world libadwaita theming practice:
 *   - window / view / headerbar / dialog  → surface   (clean base, like Adwaita)
 *   - sidebar / card / popover / overview → surface_container  (slightly elevated)
 *   - secondary_sidebar                   → surface   (no good in-between; surface is safe fallback)
 *   - error_* mirrors destructive_*       (Material You spec: error IS destructive)
 *   - backdrop / unfocused use @-refs     (avoids duplicating hex values in output)
 *   - accent_color computed by libadwaita via oklab() from accent_bg_color
 */
static const char GTK4_TEMPLATE_A[] =
    "/* Generated by mcugen — do not edit */\n"
    "/* libadwaita named-color overrides — Material You mapped to GTK4/Adwaita roles */\n"
    "\n"
    "/* ── Accent ──────────────────────────────────────────────── */\n"
    "@define-color accent_bg_color      {{colors.primary.hex}};\n"
    "@define-color accent_fg_color      {{colors.on_primary.hex}};\n"
    "/* accent_color derived by libadwaita via oklab() — do not set manually */\n"
    "\n"
    "/* ── Destructive ─────────────────────────────────────────── */\n"
    "@define-color destructive_bg_color {{colors.error.hex}};\n"
    "@define-color destructive_fg_color {{colors.on_error.hex}};\n"
    "/* Follow Material spec: error IS destructive */\n"
    "@define-color error_bg_color       {{colors.error.hex}};\n"
    "@define-color error_fg_color       {{colors.on_error.hex}};\n"
    "\n"
    "/* ── Success ─────────────────────────────────────────────── */\n"
    "@define-color success_bg_color     {{colors.tertiary.hex}};\n"
    "@define-color success_fg_color     {{colors.on_tertiary.hex}};\n"
    "\n"
    "/* ── Warning ─────────────────────────────────────────────── */\n"
    "@define-color warning_bg_color     {{colors.secondary.hex}};\n"
    "@define-color warning_fg_color     {{colors.on_secondary.hex}};\n"
    "\n"
    "/* ── Window / view / headerbar — use surface (like Adwaita) ─ */\n"
    "@define-color window_bg_color      {{colors.surface.hex}};\n"
    "@define-color window_fg_color      {{colors.on_surface.hex}};\n"
    "@define-color view_bg_color        {{colors.surface.hex}};\n"
    "@define-color view_fg_color        {{colors.on_surface.hex}};\n"
    "@define-color headerbar_bg_color           {{colors.surface.hex}};\n"
    "@define-color headerbar_fg_color           {{colors.on_surface.hex}};\n"
    "@define-color headerbar_border_color       {{colors.on_surface.hex}};\n"
    "@define-color headerbar_backdrop_color     @window_bg_color;\n"
    "@define-color headerbar_shade_color        {{colors.shadow.hex}};\n"
    "@define-color headerbar_darker_shade_color {{colors.scrim.hex}};\n";

static const char GTK4_TEMPLATE_A2[] =
    "\n"
    "/* ── Sidebar / card / popover — use surface_container ───────── */\n"
    "@define-color sidebar_bg_color             {{colors.surface_container.hex}};\n"
    "@define-color sidebar_fg_color             {{colors.on_surface.hex}};\n"
    "@define-color sidebar_backdrop_color       @sidebar_bg_color;\n"
    "@define-color sidebar_shade_color          {{colors.shadow.hex}};\n"
    "@define-color sidebar_border_color         {{colors.outline_variant.hex}};\n"
    "/* surface fallback — no good M3 in-between for secondary sidebar */\n"
    "@define-color secondary_sidebar_bg_color       {{colors.surface.hex}};\n"
    "@define-color secondary_sidebar_fg_color       {{colors.on_surface.hex}};\n"
    "@define-color secondary_sidebar_backdrop_color @secondary_sidebar_bg_color;\n"
    "@define-color secondary_sidebar_shade_color    {{colors.shadow.hex}};\n"
    "@define-color secondary_sidebar_border_color   {{colors.outline_variant.hex}};\n"
    "@define-color card_bg_color                {{colors.surface_container.hex}};\n"
    "@define-color card_fg_color                {{colors.on_surface.hex}};\n"
    "@define-color card_shade_color             {{colors.shadow.hex}};\n"
    "@define-color overview_bg_color            {{colors.surface_container.hex}};\n"
    "@define-color overview_fg_color            {{colors.on_surface.hex}};\n"
    "@define-color popover_bg_color             {{colors.surface_container.hex}};\n"
    "@define-color popover_fg_color             {{colors.on_surface.hex}};\n"
    "@define-color popover_shade_color          {{colors.shadow.hex}};\n"
    "/* dialog uses surface — more prominent/modal feel */\n"
    "@define-color dialog_bg_color              {{colors.surface.hex}};\n"
    "@define-color dialog_fg_color              {{colors.on_surface.hex}};\n"
    "@define-color thumbnail_bg_color           {{colors.surface_container.hex}};\n"
    "@define-color thumbnail_fg_color           {{colors.on_surface.hex}};\n"
    "\n"
    "/* ── Misc ────────────────────────────────────────────────── */\n"
    "@define-color shade_color              {{colors.shadow.hex}};\n"
    "@define-color scrollbar_outline_color  {{colors.surface.hex}};\n"
    "\n"
    "/* ── Backdrop / unfocused — @-refs avoid duplicating hex ──── */\n"
    "@define-color theme_unfocused_bg_color          @window_bg_color;\n"
    "@define-color theme_unfocused_fg_color          @window_fg_color;\n"
    "@define-color theme_unfocused_base_color        @window_bg_color;\n"
    "@define-color theme_unfocused_text_color        @view_fg_color;\n"
    "@define-color theme_unfocused_selected_bg_color @accent_bg_color;\n"
    "@define-color theme_unfocused_selected_fg_color @accent_fg_color;\n";

static const char GTK4_TEMPLATE_B[] =
    "\n"
    "/* ── Full M3 palette aliases (use in your own GTK CSS) ───── */\n"
    "@define-color primary                  {{colors.primary.hex}};\n"
    "@define-color on_primary               {{colors.on_primary.hex}};\n"
    "@define-color primary_container        {{colors.primary_container.hex}};\n"
    "@define-color on_primary_container     {{colors.on_primary_container.hex}};\n"
    "@define-color inverse_primary          {{colors.inverse_primary.hex}};\n"
    "@define-color secondary                {{colors.secondary.hex}};\n"
    "@define-color on_secondary             {{colors.on_secondary.hex}};\n"
    "@define-color secondary_container      {{colors.secondary_container.hex}};\n"
    "@define-color on_secondary_container   {{colors.on_secondary_container.hex}};\n"
    "@define-color tertiary                 {{colors.tertiary.hex}};\n"
    "@define-color on_tertiary              {{colors.on_tertiary.hex}};\n"
    "@define-color tertiary_container       {{colors.tertiary_container.hex}};\n"
    "@define-color on_tertiary_container    {{colors.on_tertiary_container.hex}};\n"
    "@define-color error                    {{colors.error.hex}};\n"
    "@define-color on_error                 {{colors.on_error.hex}};\n"
    "@define-color error_container          {{colors.error_container.hex}};\n"
    "@define-color on_error_container       {{colors.on_error_container.hex}};\n"
    "@define-color surface                  {{colors.surface.hex}};\n"
    "@define-color surface_variant          {{colors.surface_variant.hex}};\n"
    "@define-color on_surface               {{colors.on_surface.hex}};\n"
    "@define-color on_surface_variant       {{colors.on_surface_variant.hex}};\n"
    "@define-color surface_container_lowest  {{colors.surface_container_lowest.hex}};\n"
    "@define-color surface_container_low     {{colors.surface_container_low.hex}};\n"
    "@define-color surface_container         {{colors.surface_container.hex}};\n"
    "@define-color surface_container_high    {{colors.surface_container_high.hex}};\n"
    "@define-color surface_container_highest {{colors.surface_container_highest.hex}};\n"
    "@define-color outline                  {{colors.outline.hex}};\n"
    "@define-color outline_variant          {{colors.outline_variant.hex}};\n"
    "@define-color inverse_surface          {{colors.inverse_surface.hex}};\n";

static const char GTK4_TEMPLATE_C[] =
    "@define-color inverse_on_surface       {{colors.inverse_on_surface.hex}};\n"
    "@define-color background               {{colors.background.hex}};\n"
    "@define-color on_background            {{colors.on_background.hex}};\n";

/* ── GTK-3 template ──────────────────────────────────────────────────────── */
static const char GTK3_TEMPLATE[] =
    "/* Generated by mcugen — do not edit */\n"
    "/* GTK3 named colors mapped from Material You roles */\n"
    "\n"
    "/* ── Theme palette ───────────────────────────────────────── */\n"
    "@define-color theme_bg_color                    {{colors.surface.hex}};\n"
    "@define-color theme_fg_color                    {{colors.on_surface.hex}};\n"
    "@define-color theme_base_color                  {{colors.surface_container_lowest.hex}};\n"
    "@define-color theme_text_color                  {{colors.on_surface.hex}};\n"
    "@define-color theme_selected_bg_color           {{colors.primary.hex}};\n"
    "@define-color theme_selected_fg_color           {{colors.on_primary.hex}};\n"
    "\n"
    "/* ── Unfocused — @-refs prevent white flash on window unfocus ── */\n"
    "@define-color theme_unfocused_bg_color          @theme_bg_color;\n"
    "@define-color theme_unfocused_fg_color          @theme_fg_color;\n"
    "@define-color theme_unfocused_base_color        @theme_bg_color;\n"
    "@define-color theme_unfocused_text_color        @theme_text_color;\n"
    "@define-color theme_unfocused_selected_bg_color @theme_selected_bg_color;\n"
    "@define-color theme_unfocused_selected_fg_color @theme_selected_fg_color;\n"
    "\n"
    "/* ── Insensitive (disabled) ──────────────────────────────── */\n"
    "@define-color insensitive_bg_color              {{colors.surface_container.hex}};\n"
    "@define-color insensitive_fg_color              {{colors.on_surface_variant.hex}};\n"
    "@define-color insensitive_base_color            {{colors.surface_container_low.hex}};\n"
    "\n"
    "/* ── Borders ─────────────────────────────────────────────── */\n"
    "@define-color borders                           {{colors.outline_variant.hex}};\n"
    "@define-color unfocused_borders                 {{colors.outline_variant.hex}};\n"
    "\n"
    "/* ── Links ───────────────────────────────────────────────── */\n"
    "@define-color link_color                        {{colors.primary.hex}};\n"
    "@define-color link_visited_color                {{colors.tertiary.hex}};\n"
    "\n"
    "/* ── Tooltip ─────────────────────────────────────────────── */\n"
    "@define-color tooltip_bg_color                  {{colors.surface_container_highest.hex}};\n"
    "@define-color tooltip_fg_color                  {{colors.on_surface.hex}};\n"
    "\n"
    "/* ── Status ──────────────────────────────────────────────── */\n"
    "@define-color error_color                       {{colors.error.hex}};\n"
    "@define-color warning_color                     {{colors.secondary.hex}};\n"
    "@define-color success_color                     {{colors.tertiary.hex}};\n"
    "\n"
    "/* ── Window manager decorations ──────────────────────────── */\n"
    "@define-color wm_title                          {{colors.on_surface.hex}};\n"
    "@define-color wm_unfocused_title                {{colors.on_surface_variant.hex}};\n"
    "@define-color wm_bg                             {{colors.surface_container.hex}};\n"
    "@define-color wm_button_hover_color             {{colors.primary_container.hex}};\n";

/* ── GTK reload hook ─────────────────────────────────────────────────────── */
static const char GTK_RELOAD_HOOK[] =
    "#!/bin/sh\n"
    "# mcugen GTK reload hook\n"
    "# Forces running GTK3/GTK4/libadwaita apps to re-read CSS by toggling\n"
    "# gsettings properties that apps watch via GtkSettings / AdwStyleManager.\n"
    "\n"
    "if command -v gsettings >/dev/null 2>&1; then\n"
    "    # Capture current values\n"
    "    _THEME=$(gsettings get org.gnome.desktop.interface gtk-theme 2>/dev/null | tr -d \"'\")\n"
    "    _SCHEME=$(gsettings get org.gnome.desktop.interface color-scheme 2>/dev/null | tr -d \"'\")\n"
    "\n"
    "    # Toggle gtk-theme — triggers GtkSettings:notify::gtk-theme in GTK3/GTK4\n"
    "    gsettings set org.gnome.desktop.interface gtk-theme '' 2>/dev/null\n"
    "    gsettings set org.gnome.desktop.interface gtk-theme \"$_THEME\" 2>/dev/null\n"
    "\n"
    "    # Toggle color-scheme — triggers AdwStyleManager reload in libadwaita apps\n"
    "    if [ \"$_SCHEME\" = 'prefer-dark' ]; then\n"
    "        gsettings set org.gnome.desktop.interface color-scheme 'default' 2>/dev/null\n"
    "    else\n"
    "        gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark' 2>/dev/null\n"
    "    fi\n"
    "    sleep 0.05\n"
    "    gsettings set org.gnome.desktop.interface color-scheme \"$_SCHEME\" 2>/dev/null\n"
    "fi\n"
    "\n"
    "# xdg-desktop-portal: nudge Settings portal so Flatpak apps pick up changes\n"
    "if command -v gdbus >/dev/null 2>&1; then\n"
    "    gdbus call --session \\\n"
    "        --dest org.freedesktop.portal.Desktop \\\n"
    "        --object-path /org/freedesktop/portal/desktop \\\n"
    "        --method org.freedesktop.DBus.Properties.GetAll \\\n"
    "        org.freedesktop.portal.Settings >/dev/null 2>&1 || true\n"
    "fi\n";

/* ── Config.toml ─────────────────────────────────────────────────────────── */
static const char GTK_CONFIG[] =
    "# mcugen v3 — GTK / libadwaita configuration\n"
    "# ~/.config/mcugen/config.toml\n"
    "\n"
    "[config]\n"
    "default_mode = \"light\"       # light | dark\n"
    "default_type = \"tonal-spot\"  # tonal-spot | vibrant | expressive | fidelity\n"
    "#                             # monochrome | neutral | fruit-salad | rainbow\n"
    "caching      = false\n"
    "\n"
    "[templates.gtk4]\n"
    "input_path  = \"~/.config/mcugen/templates/gtk4.css\"\n"
    "output_path = \"~/.config/gtk-4.0/gtk.css\"\n"
    "post_hook   = \"~/.config/mcugen/hooks/gtk-reload.sh\"\n"
    "\n"
    "[templates.gtk3]\n"
    "input_path  = \"~/.config/mcugen/templates/gtk3.css\"\n"
    "output_path = \"~/.config/gtk-3.0/gtk.css\"\n"
    "\n"
    "# ---- Custom colors (optionally harmonized to seed) ----\n"
    "# [colors.green]\n"
    "# color = \"#4CAF50\"\n"
    "# blend = true\n"
    "\n"
    "# ---- Extra templates ----\n"
    "# [templates.waybar]\n"
    "# input_path  = \"~/.config/mcugen/templates/waybar.css\"\n"
    "# output_path = \"~/.config/waybar/style.css\"\n"
    "# post_hook   = \"pkill -SIGUSR2 waybar\"\n";

void cmd_init(void) {
    char cfgdir[MAX_PATH];   xdg_config_dir(cfgdir, sizeof(cfgdir));
    char cfgpath[MAX_PATH];  snprintf(cfgpath,  sizeof(cfgpath),  "%s/config.toml",   cfgdir);
    char tpldir[MAX_PATH];   snprintf(tpldir,   sizeof(tpldir),   "%s/templates",      cfgdir);
    char hookdir[MAX_PATH];  snprintf(hookdir,  sizeof(hookdir),  "%s/hooks",          cfgdir);
    char gtk4tpl[MAX_PATH];  snprintf(gtk4tpl,  sizeof(gtk4tpl),  "%s/gtk4.css",       tpldir);
    char gtk3tpl[MAX_PATH];  snprintf(gtk3tpl,  sizeof(gtk3tpl),  "%s/gtk3.css",       tpldir);
    char hookpath[MAX_PATH]; snprintf(hookpath, sizeof(hookpath), "%s/gtk-reload.sh",  hookdir);

    mkdirs_local(tpldir);
    mkdirs_local(hookdir);

    /* config.toml */
    if (access(cfgpath, F_OK) == 0) {
        printf("exists (skipping): %s\n", cfgpath);
    } else {
        write_file(cfgpath, GTK_CONFIG);
        printf("created: %s\n", cfgpath);
    }

    /* templates/gtk4.css */
    if (access(gtk4tpl, F_OK) == 0) {
        printf("exists (skipping): %s\n", gtk4tpl);
    } else {
        /* split across three string literals to stay within ISO C99 4095-char limit */
        size_t la  = strlen(GTK4_TEMPLATE_A),  la2 = strlen(GTK4_TEMPLATE_A2),
               lb  = strlen(GTK4_TEMPLATE_B),  lc  = strlen(GTK4_TEMPLATE_C);
        char *gtk4buf = malloc(la + la2 + lb + lc + 1);
        if (gtk4buf) {
            size_t off = 0;
            memcpy(gtk4buf + off, GTK4_TEMPLATE_A,  la);  off += la;
            memcpy(gtk4buf + off, GTK4_TEMPLATE_A2, la2); off += la2;
            memcpy(gtk4buf + off, GTK4_TEMPLATE_B,  lb);  off += lb;
            memcpy(gtk4buf + off, GTK4_TEMPLATE_C,  lc + 1);
            write_file(gtk4tpl, gtk4buf);
            free(gtk4buf);
        }
        printf("created: %s\n", gtk4tpl);
    }

    /* templates/gtk3.css */
    if (access(gtk3tpl, F_OK) == 0) {
        printf("exists (skipping): %s\n", gtk3tpl);
    } else {
        write_file(gtk3tpl, GTK3_TEMPLATE);
        printf("created: %s\n", gtk3tpl);
    }

    /* hooks/gtk-reload.sh */
    if (access(hookpath, F_OK) == 0) {
        printf("exists (skipping): %s\n", hookpath);
    } else {
        write_file(hookpath, GTK_RELOAD_HOOK);
        char cmd[MAX_PATH + 16];
        snprintf(cmd, sizeof(cmd), "chmod +x %s", hookpath);
        int r = system(cmd); (void)r;
        printf("created: %s\n", hookpath);
    }

    /* ensure GTK output dirs exist */
    const char *home = real_home();
    char gtk4dir[MAX_PATH]; snprintf(gtk4dir, sizeof(gtk4dir), "%s/.config/gtk-4.0", home);
    char gtk3dir[MAX_PATH]; snprintf(gtk3dir, sizeof(gtk3dir), "%s/.config/gtk-3.0", home);
    mkdirs_local(gtk4dir);
    mkdirs_local(gtk3dir);
    printf("ready:   %s\n", gtk4dir);
    printf("ready:   %s\n", gtk3dir);

    printf("\nQuick start:\n");
    printf("  mcugen color \"#6750A4\"              # light → gtk3 + gtk4\n");
    printf("  mcugen color \"#6750A4\" --mode dark  # dark scheme\n");
    printf("  mcugen image ~/Pictures/wall.jpg    # seed from wallpaper\n");
    printf("  mcugen blend \"#6750A4\" \"#1DB954\"    # blend two seeds\n");
    printf("  mcugen save mytheme                 # save profile\n");
    printf("  mcugen check                        # validate config\n");
    printf("\nHook: %s\n", hookpath);
    printf("Runs after every generation — reloads GTK3/GTK4/libadwaita apps live.\n");
}
