#define _POSIX_C_SOURCE 200809L
#define _GNU_SOURCE
#pragma GCC diagnostic ignored "-Wunused-result"

#include "reload.h"
#include "../util/log.h"
#include "../util/paths.h"
#include "../util/fs.h"
#include "../mcugen.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

void save_hooks_cache(const Config *cfg) {
    char dir[MAX_PATH]; xdg_cache_dir(dir, sizeof(dir));
    mkdirs_local(dir);
    char hp[MAX_PATH]; snprintf(hp, sizeof(hp), "%s/hooks.sh", dir);
    FILE *f = fopen(hp, "wb");
    if (!f) return;
    fprintf(f, "#!/bin/sh\n# Auto-generated by mcugen — do not edit\n");
    for (int i = 0; i < cfg->n_templates; i++) {
        const TemplateConfig *tc = &cfg->templates[i];
        if (tc->has_post_hook)
            fprintf(f, "%s\n", tc->post_hook);
    }
    fclose(f);
    chmod(hp, 0755);
}

void cmd_reload(void) {
    char dir[MAX_PATH]; xdg_cache_dir(dir, sizeof(dir));
    char hp[MAX_PATH]; snprintf(hp, sizeof(hp), "%s/hooks.sh", dir);
    if (access(hp, F_OK) != 0)
        die("no cached hooks found. Run mcugen once first.");
    printf("Running cached post-hooks...\n");
    int ret = system(hp);
    if (ret != 0) warn("hooks exited with code %d", ret);
    else          printf("Done.\n");
}
