#include "help.h"
#include "../mcugen.h"
#include <stdio.h>

void print_usage(void) {
    printf(
        "\033[1mmcugen\033[0m " MCUGEN_VERSION " — Material You color scheme generator\n"
        "\n"
        "\033[1mUSAGE\033[0m\n"
        "  mcugen <command> [options]\n"
        "\n"
        "\033[1mCOMMANDS\033[0m\n"
        "  color  <#hex>            Generate scheme from hex color\n"
        "  image  <path>            Generate scheme from image dominant color\n"
        "  blend  <#hex> <#hex>     Blend two seed colors → generate scheme\n"
        "  show   color|image       Preview scheme without writing files\n"
        "  save   <name>            Save current seed as named profile\n"
        "  use    <name>            Apply a saved profile\n"
        "  profiles                 List saved profiles\n"
        "  check                    Validate config and templates\n"
        "  reload                   Re-run post hooks for last scheme\n"
        "  watch  <dir>             Watch directory for new images\n"
        "  init                     Create default config and template\n"
        "\n"
        "\033[1mOPTIONS\033[0m\n"
        "  --mode    light|dark     Color scheme mode        (default: light)\n"
        "  --type    <variant>      Scheme variant           (default: tonal-spot)\n"
        "  --contrast <-1..1>       Contrast adjustment      (default: 0)\n"
        "  --export  figma|material Export tokens as JSON\n"
        "  --json                   Print full scheme as JSON\n"
        "  --swatch                 Print ANSI true-color swatches\n"
        "  --config  <path>         Custom config file path\n"
        "  -v, --verbose            Verbose output\n"
        "  -q, --quiet              Suppress output\n"
        "  --strict                 Exit 1 on any warning\n"
        "  --version                Print version\n"
        "\n"
        "\033[1mSCHEME TYPES\033[0m\n"
        "  tonal-spot  vibrant  expressive  fidelity  monochrome\n"
        "  neutral  fruit-salad  rainbow  content\n"
        "\n"
        "\033[1mEXAMPLES\033[0m\n"
        "  mcugen color \"#6750A4\"\n"
        "  mcugen image ~/Pictures/wall.jpg --mode dark --type vibrant\n"
        "  mcugen blend \"#6750A4\" \"#1DB954\" --swatch\n"
        "  mcugen color \"#6750A4\" --export figma -o tokens.json\n"
        "  mcugen save mywall && mcugen use mywall\n"
    );
}
